### ISSUE TITLE
InsertNewlineAtEndOfFile broken

### ISSUE THREAD

**Issue by muratbolu** [kkKaan/general-clang-format#1]
The new versions of clang-format changed the name of InsertNewlineAtEndOfFile to [InsertNewlineAtEOF](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertnewlineateof). The old version does not work anymore. It is at line 154 of `.clang-format`.
```
@@ -151,7 +151,7 @@ IndentWrappedFunctionNames: true
 # JavaScriptWrapImports: true

 # InsertBraces: true -> safer to do manually
-InsertNewlineAtEOF: true
+InsertNewlineAtEndOfFile: true
 InsertTrailingCommas: None # Wrapped

 # IntegerLiteralSeperator:
```

**Comment by kkKaan** [comment]
Thanks for the update, it is fixed now.
